### PR TITLE
Andresp

### PR DESCRIPTION
**Pull request by apombo90**
Done with cleaning and transforming the data. Also exported two new CSV files.
1.  'heart_clean.csv' which is the data without creating the variables for the text features. (This one should be the one 
2.  'heart_dummies.csv' which is the data after using get_dummies() function. We will be using this CSV file to create the ML model.

### CODE REVIEW

**Comment by apombo90** [comment]
@Rangisal Please review 😄

**Comment by apombo90** [comment]
Also, created a new notebook for our Logistic Regression Model, imported the data, removed the target column from the features data, and split the training and test data sets. 
@Rangisal Please review this one as well 🤓

**Comment by Rangisal** [comment]
I will thanks :)

**Review by Rangisal — COMMENTED** [review]
reviewed the removing duplicates

**Review by Rangisal — COMMENTED** [review]
Reviewed the string column

**Review by Rangisal — COMMENTED** [review]
Reviewed the BMI column

**Review by Rangisal — COMMENTED** [review]
Reviewed

**Pull request merged**
